/* automatically generated by rust-bindgen 0.72.1 */

// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Generated declarations from vendor/asr.h; loader normalized for libloading 0.9 by tools/regenerate.sh.

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_recognizer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_stream {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_result {
    _unused: [u8; 0],
}
pub const NEMO_SPEECH_ASR_OK: nemo_speech_asr_status = 0;
pub const NEMO_SPEECH_ASR_ERROR_INVALID_ARGUMENT: nemo_speech_asr_status = 1;
pub const NEMO_SPEECH_ASR_ERROR_OUT_OF_MEMORY: nemo_speech_asr_status = 2;
pub const NEMO_SPEECH_ASR_ERROR_RUNTIME: nemo_speech_asr_status = 3;
pub const NEMO_SPEECH_ASR_ERROR_CANCELLED: nemo_speech_asr_status = 4;
pub type nemo_speech_asr_status = ::std::os::raw::c_uint;
pub const NEMO_SPEECH_ASR_DECODER_GREEDY: nemo_speech_asr_decoder_kind = 0;
pub const NEMO_SPEECH_ASR_DECODER_FLASHLIGHT: nemo_speech_asr_decoder_kind = 1;
pub type nemo_speech_asr_decoder_kind = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nemo_speech_asr_backend_config {
    pub size: usize,
    pub gpu: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_model_config {
    pub size: usize,
    pub path: *const ::std::os::raw::c_char,
    pub name: *const ::std::os::raw::c_char,
}
impl Default for nemo_speech_asr_model_config {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nemo_speech_asr_streaming_config {
    pub size: usize,
    pub chunk_size: f32,
    pub ctc_left_padding: f32,
    pub ctc_right_padding: f32,
    pub rnnt_right_context: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_decoder_config {
    pub size: usize,
    pub kind: nemo_speech_asr_decoder_kind,
    pub flashlight_lm: *const ::std::os::raw::c_char,
    pub flashlight_lexicon: *const ::std::os::raw::c_char,
    pub flashlight_tokenizer: *const ::std::os::raw::c_char,
    pub beam_size: i32,
    pub beam_size_token: i32,
    pub beam_threshold: f64,
    pub lm_weight: f64,
    pub word_insertion_score: f64,
    pub max_boost: f64,
}
impl Default for nemo_speech_asr_decoder_config {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_vad_config {
    pub size: usize,
    pub model_path: *const ::std::os::raw::c_char,
    pub enable_masking: bool,
    pub onset: f32,
    pub offset: f32,
}
impl Default for nemo_speech_asr_vad_config {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nemo_speech_asr_endpointing_config {
    pub size: usize,
    pub enable: bool,
    pub vad_based: bool,
    pub stop_history_eou_ms: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_postproc_config {
    pub size: usize,
    pub profanity_list_path: *const ::std::os::raw::c_char,
    pub itn_model_dir: *const ::std::os::raw::c_char,
    pub pnc_model_path: *const ::std::os::raw::c_char,
}
impl Default for nemo_speech_asr_postproc_config {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_diar_config {
    pub size: usize,
    pub model_path: *const ::std::os::raw::c_char,
    pub chunk_frames: i32,
    pub right_context_frames: i32,
    pub left_context_frames: i32,
    pub fifo_frames: i32,
    pub spkcache_frames: i32,
    pub update_period_frames: i32,
}
impl Default for nemo_speech_asr_diar_config {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nemo_speech_asr_batching_config {
    pub size: usize,
    pub enable: bool,
    pub max_batch_size: i32,
    pub max_queue_delay_us: i32,
    pub max_queue_depth: i32,
    pub ingress_cohort_delay_us: i32,
    pub state_arena_slots: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_recognizer_config {
    pub size: usize,
    pub backend: *const nemo_speech_asr_backend_config,
    pub model: *const nemo_speech_asr_model_config,
    pub streaming: *const nemo_speech_asr_streaming_config,
    pub decoder: *const nemo_speech_asr_decoder_config,
    pub vad: *const nemo_speech_asr_vad_config,
    pub endpointing: *const nemo_speech_asr_endpointing_config,
    pub postproc: *const nemo_speech_asr_postproc_config,
    pub diar: *const nemo_speech_asr_diar_config,
    pub batching: *const nemo_speech_asr_batching_config,
}
impl Default for nemo_speech_asr_recognizer_config {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_speech_context {
    pub size: usize,
    pub phrases: *const *const ::std::os::raw::c_char,
    pub phrase_count: usize,
    pub boost: f32,
}
impl Default for nemo_speech_asr_speech_context {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_speech_asr_recognition_options {
    pub size: usize,
    pub request_id: *const ::std::os::raw::c_char,
    pub language_code: *const ::std::os::raw::c_char,
    pub interim_results: bool,
    pub enable_word_time_offsets: bool,
    pub enable_automatic_punctuation: bool,
    pub verbatim_transcripts: bool,
    pub profanity_filter: bool,
    pub stop_history_eou_ms: i32,
    pub speech_contexts: *const nemo_speech_asr_speech_context,
    pub speech_context_count: usize,
    pub max_alternatives: i32,
    pub enable_speaker_diarization: bool,
    pub max_speaker_count: i32,
}
impl Default for nemo_speech_asr_recognition_options {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub struct NativeApi {
    __library: ::libloading::Library,
    pub nemo_speech_asr_recognition_options_default:
        unsafe extern "C" fn() -> nemo_speech_asr_recognition_options,
    pub nemo_speech_asr_create: unsafe extern "C" fn(
        cfg: *const nemo_speech_asr_recognizer_config,
        out: *mut *mut nemo_speech_asr_recognizer,
    ) -> nemo_speech_asr_status,
    pub nemo_speech_asr_destroy: unsafe extern "C" fn(recognizer: *mut nemo_speech_asr_recognizer),
    pub nemo_speech_asr_recognize_f32: unsafe extern "C" fn(
        recognizer: *mut nemo_speech_asr_recognizer,
        options: *const nemo_speech_asr_recognition_options,
        samples: *const f32,
        n_samples: usize,
        sample_rate: i32,
        out: *mut *mut nemo_speech_asr_result,
    ) -> nemo_speech_asr_status,
    pub nemo_speech_asr_streaming_recognize: unsafe extern "C" fn(
        recognizer: *mut nemo_speech_asr_recognizer,
        options: *const nemo_speech_asr_recognition_options,
        out: *mut *mut nemo_speech_asr_stream,
    ) -> nemo_speech_asr_status,
    pub nemo_speech_asr_stream_push_f32: unsafe extern "C" fn(
        stream: *mut nemo_speech_asr_stream,
        samples: *const f32,
        n_samples: usize,
        sample_rate: i32,
    ) -> nemo_speech_asr_status,
    pub nemo_speech_asr_stream_force_endpoint:
        unsafe extern "C" fn(stream: *mut nemo_speech_asr_stream) -> nemo_speech_asr_status,
    pub nemo_speech_asr_stream_finish:
        unsafe extern "C" fn(stream: *mut nemo_speech_asr_stream) -> nemo_speech_asr_status,
    pub nemo_speech_asr_stream_next: unsafe extern "C" fn(
        stream: *mut nemo_speech_asr_stream,
        out: *mut *mut nemo_speech_asr_result,
    ) -> nemo_speech_asr_status,
    pub nemo_speech_asr_stream_close: unsafe extern "C" fn(stream: *mut nemo_speech_asr_stream),
    pub nemo_speech_asr_result_is_final:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result) -> bool,
    pub nemo_speech_asr_result_audio_processed:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result) -> f32,
    pub nemo_speech_asr_result_channel_tag:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result) -> i32,
    pub nemo_speech_asr_result_alternative_count:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result) -> usize,
    pub nemo_speech_asr_result_transcript: unsafe extern "C" fn(
        result: *const nemo_speech_asr_result,
        alt: usize,
    )
        -> *const ::std::os::raw::c_char,
    pub nemo_speech_asr_result_confidence:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize) -> f32,
    pub nemo_speech_asr_result_word_count:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize) -> usize,
    pub nemo_speech_asr_result_word_text: unsafe extern "C" fn(
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    )
        -> *const ::std::os::raw::c_char,
    pub nemo_speech_asr_result_word_start_time:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize, i: usize) -> i32,
    pub nemo_speech_asr_result_word_end_time:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize, i: usize) -> i32,
    pub nemo_speech_asr_result_word_confidence:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize, i: usize) -> f32,
    pub nemo_speech_asr_result_word_speaker_tag:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize, i: usize) -> i32,
    pub nemo_speech_asr_result_language_count:
        unsafe extern "C" fn(result: *const nemo_speech_asr_result, alt: usize) -> usize,
    pub nemo_speech_asr_result_language_code: unsafe extern "C" fn(
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    )
        -> *const ::std::os::raw::c_char,
    pub nemo_speech_asr_result_destroy: unsafe extern "C" fn(result: *mut nemo_speech_asr_result),
    pub nemo_speech_asr_last_error: unsafe extern "C" fn() -> *const ::std::os::raw::c_char,
    pub nemo_speech_asr_version: unsafe extern "C" fn() -> *const ::std::os::raw::c_char,
}
impl NativeApi {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = unsafe { ::libloading::Library::new(path.as_ref()) }?;
        unsafe { Self::from_library(library) }
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let nemo_speech_asr_recognition_options_default =
            unsafe { __library.get(b"nemo_speech_asr_recognition_options_default\0") }
                .map(|sym| *sym)?;
        let nemo_speech_asr_create =
            unsafe { __library.get(b"nemo_speech_asr_create\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_destroy =
            unsafe { __library.get(b"nemo_speech_asr_destroy\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_recognize_f32 =
            unsafe { __library.get(b"nemo_speech_asr_recognize_f32\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_streaming_recognize =
            unsafe { __library.get(b"nemo_speech_asr_streaming_recognize\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_stream_push_f32 =
            unsafe { __library.get(b"nemo_speech_asr_stream_push_f32\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_stream_force_endpoint =
            unsafe { __library.get(b"nemo_speech_asr_stream_force_endpoint\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_stream_finish =
            unsafe { __library.get(b"nemo_speech_asr_stream_finish\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_stream_next =
            unsafe { __library.get(b"nemo_speech_asr_stream_next\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_stream_close =
            unsafe { __library.get(b"nemo_speech_asr_stream_close\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_is_final =
            unsafe { __library.get(b"nemo_speech_asr_result_is_final\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_audio_processed =
            unsafe { __library.get(b"nemo_speech_asr_result_audio_processed\0") }
                .map(|sym| *sym)?;
        let nemo_speech_asr_result_channel_tag =
            unsafe { __library.get(b"nemo_speech_asr_result_channel_tag\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_alternative_count =
            unsafe { __library.get(b"nemo_speech_asr_result_alternative_count\0") }
                .map(|sym| *sym)?;
        let nemo_speech_asr_result_transcript =
            unsafe { __library.get(b"nemo_speech_asr_result_transcript\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_confidence =
            unsafe { __library.get(b"nemo_speech_asr_result_confidence\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_word_count =
            unsafe { __library.get(b"nemo_speech_asr_result_word_count\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_word_text =
            unsafe { __library.get(b"nemo_speech_asr_result_word_text\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_word_start_time =
            unsafe { __library.get(b"nemo_speech_asr_result_word_start_time\0") }
                .map(|sym| *sym)?;
        let nemo_speech_asr_result_word_end_time =
            unsafe { __library.get(b"nemo_speech_asr_result_word_end_time\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_word_confidence =
            unsafe { __library.get(b"nemo_speech_asr_result_word_confidence\0") }
                .map(|sym| *sym)?;
        let nemo_speech_asr_result_word_speaker_tag =
            unsafe { __library.get(b"nemo_speech_asr_result_word_speaker_tag\0") }
                .map(|sym| *sym)?;
        let nemo_speech_asr_result_language_count =
            unsafe { __library.get(b"nemo_speech_asr_result_language_count\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_language_code =
            unsafe { __library.get(b"nemo_speech_asr_result_language_code\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_result_destroy =
            unsafe { __library.get(b"nemo_speech_asr_result_destroy\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_last_error =
            unsafe { __library.get(b"nemo_speech_asr_last_error\0") }.map(|sym| *sym)?;
        let nemo_speech_asr_version =
            unsafe { __library.get(b"nemo_speech_asr_version\0") }.map(|sym| *sym)?;
        Ok(NativeApi {
            __library,
            nemo_speech_asr_recognition_options_default,
            nemo_speech_asr_create,
            nemo_speech_asr_destroy,
            nemo_speech_asr_recognize_f32,
            nemo_speech_asr_streaming_recognize,
            nemo_speech_asr_stream_push_f32,
            nemo_speech_asr_stream_force_endpoint,
            nemo_speech_asr_stream_finish,
            nemo_speech_asr_stream_next,
            nemo_speech_asr_stream_close,
            nemo_speech_asr_result_is_final,
            nemo_speech_asr_result_audio_processed,
            nemo_speech_asr_result_channel_tag,
            nemo_speech_asr_result_alternative_count,
            nemo_speech_asr_result_transcript,
            nemo_speech_asr_result_confidence,
            nemo_speech_asr_result_word_count,
            nemo_speech_asr_result_word_text,
            nemo_speech_asr_result_word_start_time,
            nemo_speech_asr_result_word_end_time,
            nemo_speech_asr_result_word_confidence,
            nemo_speech_asr_result_word_speaker_tag,
            nemo_speech_asr_result_language_count,
            nemo_speech_asr_result_language_code,
            nemo_speech_asr_result_destroy,
            nemo_speech_asr_last_error,
            nemo_speech_asr_version,
        })
    }
    pub unsafe fn nemo_speech_asr_recognition_options_default(
        &self,
    ) -> nemo_speech_asr_recognition_options {
        unsafe { (self.nemo_speech_asr_recognition_options_default)() }
    }
    pub unsafe fn nemo_speech_asr_create(
        &self,
        cfg: *const nemo_speech_asr_recognizer_config,
        out: *mut *mut nemo_speech_asr_recognizer,
    ) -> nemo_speech_asr_status {
        unsafe { (self.nemo_speech_asr_create)(cfg, out) }
    }
    pub unsafe fn nemo_speech_asr_destroy(&self, recognizer: *mut nemo_speech_asr_recognizer) {
        unsafe { (self.nemo_speech_asr_destroy)(recognizer) }
    }
    pub unsafe fn nemo_speech_asr_recognize_f32(
        &self,
        recognizer: *mut nemo_speech_asr_recognizer,
        options: *const nemo_speech_asr_recognition_options,
        samples: *const f32,
        n_samples: usize,
        sample_rate: i32,
        out: *mut *mut nemo_speech_asr_result,
    ) -> nemo_speech_asr_status {
        unsafe {
            (self.nemo_speech_asr_recognize_f32)(
                recognizer,
                options,
                samples,
                n_samples,
                sample_rate,
                out,
            )
        }
    }
    pub unsafe fn nemo_speech_asr_streaming_recognize(
        &self,
        recognizer: *mut nemo_speech_asr_recognizer,
        options: *const nemo_speech_asr_recognition_options,
        out: *mut *mut nemo_speech_asr_stream,
    ) -> nemo_speech_asr_status {
        unsafe { (self.nemo_speech_asr_streaming_recognize)(recognizer, options, out) }
    }
    pub unsafe fn nemo_speech_asr_stream_push_f32(
        &self,
        stream: *mut nemo_speech_asr_stream,
        samples: *const f32,
        n_samples: usize,
        sample_rate: i32,
    ) -> nemo_speech_asr_status {
        unsafe { (self.nemo_speech_asr_stream_push_f32)(stream, samples, n_samples, sample_rate) }
    }
    pub unsafe fn nemo_speech_asr_stream_force_endpoint(
        &self,
        stream: *mut nemo_speech_asr_stream,
    ) -> nemo_speech_asr_status {
        unsafe { (self.nemo_speech_asr_stream_force_endpoint)(stream) }
    }
    pub unsafe fn nemo_speech_asr_stream_finish(
        &self,
        stream: *mut nemo_speech_asr_stream,
    ) -> nemo_speech_asr_status {
        unsafe { (self.nemo_speech_asr_stream_finish)(stream) }
    }
    pub unsafe fn nemo_speech_asr_stream_next(
        &self,
        stream: *mut nemo_speech_asr_stream,
        out: *mut *mut nemo_speech_asr_result,
    ) -> nemo_speech_asr_status {
        unsafe { (self.nemo_speech_asr_stream_next)(stream, out) }
    }
    pub unsafe fn nemo_speech_asr_stream_close(&self, stream: *mut nemo_speech_asr_stream) {
        unsafe { (self.nemo_speech_asr_stream_close)(stream) }
    }
    pub unsafe fn nemo_speech_asr_result_is_final(
        &self,
        result: *const nemo_speech_asr_result,
    ) -> bool {
        unsafe { (self.nemo_speech_asr_result_is_final)(result) }
    }
    pub unsafe fn nemo_speech_asr_result_audio_processed(
        &self,
        result: *const nemo_speech_asr_result,
    ) -> f32 {
        unsafe { (self.nemo_speech_asr_result_audio_processed)(result) }
    }
    pub unsafe fn nemo_speech_asr_result_channel_tag(
        &self,
        result: *const nemo_speech_asr_result,
    ) -> i32 {
        unsafe { (self.nemo_speech_asr_result_channel_tag)(result) }
    }
    pub unsafe fn nemo_speech_asr_result_alternative_count(
        &self,
        result: *const nemo_speech_asr_result,
    ) -> usize {
        unsafe { (self.nemo_speech_asr_result_alternative_count)(result) }
    }
    pub unsafe fn nemo_speech_asr_result_transcript(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
    ) -> *const ::std::os::raw::c_char {
        unsafe { (self.nemo_speech_asr_result_transcript)(result, alt) }
    }
    pub unsafe fn nemo_speech_asr_result_confidence(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
    ) -> f32 {
        unsafe { (self.nemo_speech_asr_result_confidence)(result, alt) }
    }
    pub unsafe fn nemo_speech_asr_result_word_count(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
    ) -> usize {
        unsafe { (self.nemo_speech_asr_result_word_count)(result, alt) }
    }
    pub unsafe fn nemo_speech_asr_result_word_text(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    ) -> *const ::std::os::raw::c_char {
        unsafe { (self.nemo_speech_asr_result_word_text)(result, alt, i) }
    }
    pub unsafe fn nemo_speech_asr_result_word_start_time(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    ) -> i32 {
        unsafe { (self.nemo_speech_asr_result_word_start_time)(result, alt, i) }
    }
    pub unsafe fn nemo_speech_asr_result_word_end_time(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    ) -> i32 {
        unsafe { (self.nemo_speech_asr_result_word_end_time)(result, alt, i) }
    }
    pub unsafe fn nemo_speech_asr_result_word_confidence(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    ) -> f32 {
        unsafe { (self.nemo_speech_asr_result_word_confidence)(result, alt, i) }
    }
    pub unsafe fn nemo_speech_asr_result_word_speaker_tag(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    ) -> i32 {
        unsafe { (self.nemo_speech_asr_result_word_speaker_tag)(result, alt, i) }
    }
    pub unsafe fn nemo_speech_asr_result_language_count(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
    ) -> usize {
        unsafe { (self.nemo_speech_asr_result_language_count)(result, alt) }
    }
    pub unsafe fn nemo_speech_asr_result_language_code(
        &self,
        result: *const nemo_speech_asr_result,
        alt: usize,
        i: usize,
    ) -> *const ::std::os::raw::c_char {
        unsafe { (self.nemo_speech_asr_result_language_code)(result, alt, i) }
    }
    pub unsafe fn nemo_speech_asr_result_destroy(&self, result: *mut nemo_speech_asr_result) {
        unsafe { (self.nemo_speech_asr_result_destroy)(result) }
    }
    pub unsafe fn nemo_speech_asr_last_error(&self) -> *const ::std::os::raw::c_char {
        unsafe { (self.nemo_speech_asr_last_error)() }
    }
    pub unsafe fn nemo_speech_asr_version(&self) -> *const ::std::os::raw::c_char {
        unsafe { (self.nemo_speech_asr_version)() }
    }
}
